# Generated by Django 3.0.3 on 2020-03-11 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatbooking',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Member'),
        ),
    ]
