# Generated by Django 3.0.3 on 2020-03-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200311_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
